version: '3.8'
services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: ragrox123/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql 
    environment:
      - MY_SQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  
  vproapp:
    build: 
      context: ./Docker-files/app
    image: ragrox123/vprofileapp
    container_name: vprodbapp
    ports:
      - "8081:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build: 
      context: ./Docker-files/web
    image: ragrox123/vprofileweb
    container_name: vprodbweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
